### ISSUE TITLE
Training BC not working

### ISSUE THREAD

**Issue by Miffyli** [minerllabs/basalt_competition_baseline_submissions#6]
It seems like the BC training code `bc.py´ is not working: https://discourse.aicrowd.com/t/error-of-running-the-bc-baseline-code/6480 . Sounds to me like one of the dependencies has had backwards-incompatible changes?

@shwang  @decodyng

**Comment by shwang** [comment]
Imitation recently united all of the Sacred experiment APIs which might
have led to this problem. Pinning the imitation install to a commit before
https://github.com/HumanCompatibleAI/imitation/commit/27fdc93a680211bf25c9403de5fdc5ccce428baa
should fix this issue.

I can propose a fix PR within 24 hours, but might not be able to test it on
my laptop.

Thanks for bringing this up!
